name: Security audit
# Temporarily disabled due to unfixed security issue in chrono package
on:
  push:
    branches:
      - not-existing-branch
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
  #schedule:
  #  - cron: "7 7 * * *"

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
